name: CI
on:
  pull_request:
jobs:
  #setup:
  #  runs-on: ubuntu-latest
  #  outputs:
  #    branch: ${{ steps.extract_branch.outputs }}
  #  steps:
  #    - name: Extract branch name
  #      shell: bash
  #      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
  #      id: extract_branch
  pkg_deployment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configuration GIT name
      run: git config --global user.name ${{secrets.BOT_NAME}}
    - name: Configuration GIT email
      run: git config --global user.email ${{secrets.BOT_EMAIL}}
    - name: Creating .npmrc file
      run: echo "registry=https://registry.npmjs.org/" >> ~/.npmrc && echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" >> ~/.npmrc
      env:
        NPM_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
    - name: Setting up the environment
      run: npm install && npm run build && sudo npm link
    - name: Deploying version
      run: sudo npm-deploy npm-package-deployer --dry-run --publish-pretty-output
  action_deployment:
    needs: setup 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setting up the environment
      run: npm install && npm run build && sudo npm link
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - run: echo "${{ steps.extract_branch.outputs.branch }}"
    
    - name: Deploying version
      uses: danitseitlin/npm-package-deployer@master
      #env: 
      #  branch: ${{ steps.extract_branch.outputs.branch }}
      with:
        pkg_name: npm-package-deployer
        pkg_registry: https://registry.npmjs.org/
        npm_access_token: ${{secrets.NPM_AUTH_TOKEN}}
        dry_run: true
      