name: Deploy Bot
on:
  push:
    branches: [ master ]
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setting up the environment
      run: npm install && npm run build && sudo npm link
    - name: Deploying version
      uses: danitseitlin/npm-package-deployer@master
      with:
        pkg_name: npm-package-deployer
        pkg_registry: registry.npmjs.org
        npm_access_token: ${{secrets.NPM_AUTH_TOKEN}}
        github_access_token: ${{secrets.GITHUB_ACCESS_TOKEN}}
        github_repo_url: https://github.com/danitseitlin/npm-package-deployer